# -*- coding: utf-8 -*-
"""data_prep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3nAlVPOpPMdmwF7L9HZ1NL3sqLUNBus
"""

!pip install pandas
!pip install numpy
!pip install seaborn
!pip install matplotlib
!pip install scikit-learn

import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder


df = pd.read_csv('onlinefraud.csv')

# Encoding Transaction Type
type_mapping = {
    'PAYMENT': 1,
    'TRANSFER': 2,
    'CASH_OUT': 3,
    'DEBIT': 4,
    'CASH_IN': 5
}
df['type_encoded'] = df['type'].map(type_mapping)

# Label Encoding
le = LabelEncoder()
df['nameOrig_encoded'] = le.fit_transform(df['nameOrig'])
df['nameDest_encoded'] = le.fit_transform(df['nameDest'])

# Drop unnecessary columns
df.drop(['nameOrig', 'nameDest', 'isFlaggedFraud', 'type'], axis=1, inplace=True)

# Column Standardization
cols_to_standardize = ['amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']
scaler = StandardScaler()
df[cols_to_standardize] = scaler.fit_transform(df[cols_to_standardize])

# Display the cleaned data
print(df.head())

# Save the cleaned data
df.to_csv('cleaned_data.csv', index=False)
print("Cleaned data saved to 'cleaned_data.csv'.")